### PR TITLE
Rob Norris 2024 :guitar:

### PR DESCRIPTION
**Pull request by robn**

### CODE REVIEW

**Comment by 0mp** [comment]
Thanks!

**Comment by ppaeps** [comment]
Any idea why this one is breaking the CI build?  It looks like the production build is fine.

**Comment by 0mp** [comment]
I suspect that we updated Hugo or something and now it is more strict.

Look:

```
ERROR invalid front matter: date: 2019-08-18 14:00 ~ 14:40: see /tmp/cirrus-build/content/2019/COSCUP/benedict-Telegraf-InfluxDB-Grafana.md
ERROR invalid front matter: date: 2019-08-18 15:30 ~ 16:00: see /tmp/cirrus-build/content/2019/COSCUP/lwhsu-getting-started.md
ERROR invalid front matter: date: 2019-10-15 10:50 ~ 11:35: see /tmp/cirrus-build/content/2019/COSCUP/philip-ZFS-filesystem.md
```

(https://github.com/freebsd/freebsd-papers/runs/31492409077)

The `date` fields in the front matter of the 2019 COSCUP talks contain the exact time when the talks happened. This is not supported by our front matter. 

In other words, Rob's PR is fine I think. It's just that our old talks require patching.

**Comment by 0mp** [comment]
https://github.com/freebsd/freebsd-papers/pull/146

**Pull request merged**
