### PR TITLE
Scheduling Priorities in FreeBSD (AsiaBSDCon 2024, Olivier Certner)

### PR DESCRIPTION
**Pull request by OlCe2**

### CODE REVIEW

**Comment by ppaeps** [comment]
Looks good to me.  Thank you!

Do you have write access to the repo to rebase+merge yourself?  Or do I need to wave another appropriately shaped chicken at GitHub's access controls? :-)

**Review by ppaeps — APPROVED** [review]

**Comment by OlCe2** [comment]
Seems I can, yes.  Thanks.

Out of curiosity, when is the web site updated?  So that I can double-check that indeed nothing is messed up.

**Comment by ppaeps** [comment]
It should be updated every half hour:

```
7,37 * * * * /usr/local/www/papers/update.sh
```

**Comment by OlCe2** [comment]
Double-checked and everything seems OK.

**Pull request merged**
